version: "3.1"

networks:
  web:
    external: true

services:
  saved:
    build: .
    container_name: saved
    restart: always
    env_file:
      - .env
    volumes:
      - ./uploads:/uploads
    labels:
      - "traefik.backend=saved"
      - "traefik.domain=kumpf.io"
      - "traefik.frontend.rule=Host:saved.kumpf.io"
      - "traefik.frontend.redirect.entryPoint=https"
      - "traefik.docker.network=web"
      - "traefik.port=4444"
    networks:
      - web
