version: "3.1"

networks:
  web:
    external: true

services:
  saveddev:
    build: .
    container_name: saveddev
    ports:
      - "4444:4444"
    working_dir: /app
    env_file:
      - .env
    labels:
      - traefik.enable=false
    networks:
      - web

