version: "3.1"

networks:
  web:
    external: true

services:
  saved:
    build: .
    container_name: saved
    restart: always
    environment:
      - SERVER_PORT=4444
      - LOGLEVEL=production
      - MONGO_DB=wbag
      - MONGO_ADDRS=mongodb://mongodb:27017/
    volumes:
      - ./uploads:/uploads
    labels:
      - "traefik.backend=saved"
      - "traefik.domain=kumpf.io"
      - "traefik.frontend.rule=Host:saved.kumpf.io"
      - "traefik.frontend.redirect.entryPoint=https"
      - "traefik.docker.network=web"
      - "traefik.port=4444"
    networks:
      - web
